version: '3'

services:

  nginx:
    container_name: ${APP_PROJECT}-nginx
    image: nginx:stable-alpine
    env_file:
      - .env
    volumes:
      - .:/var/www/app
      - ./.docker/config/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./.docker/logs/nginx:/var/log/nginx
    networks:
      - internal
      - web
    labels:
      - "traefik.http.routers.${APP_PROJECT}.rule=Host(`${APP_URL}`)"
      - "traefik.http.services.${APP_PROJECT}-service.loadbalancer.server.port=80"
    depends_on:
      - php-fpm

  php-fpm:
    container_name: ${APP_PROJECT}-php-fpm
    build: .docker/php
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - .:/var/www/
    networks:
      - internal
    depends_on:
        - db

    # docker-compose run --rm console secrets:set --local
  console:
    container_name: ${APP_PROJECT}-console
    build:
      context: .
      build: .docker/php
    volumes:
      - .:/var/www
    entrypoint: ['/var/www/bin/console']
    networks:
      - internal

  db:
    container_name: ${APP_PROJECT}-db
    image: mysql:8.0.22
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
        - "3306:3306"
    environment:
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        - TZ=Europe/Paris
    volumes:
        - ./.docker/database:/var/lib/mysql
    networks:
        - internal

networks:
  web:
    external: true
  internal:
    driver: bridge
