version: '2'
services:
    db:
        container_name: symfony_db
        image: mysql:8.0.22
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        volumes:
        - .docker/db/data:/var/lib/mysql

    php:
        container_name: symfony_php-fpm
        build: .docker/php
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}?serverVersion=5.7
        volumes:
            - .:/var/www/
        depends_on: 
            - db

    nginx:
        container_name: symfony_nginx
        build: .docker/nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on: 
            - php
        volumes:
            - .:/var/www
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .docker/nginx/sites/:/etc/nginx/sites-available
            - .docker/nginx/conf.d/:/etc/nginx/conf.d
